[sink_flac] missing SWAPS definition
On big endian architecture with libflac enabled the following error
would happen when cross-compiling aubio with buildroot.

```
[ 75/243] Linking build/tests/test-pitchshift
/home/autobuild/autobuild/instance-16/output-1/per-package/aubio/host/bin/../lib/gcc/mips64-buildroot-linux-gnu/13.3.0/../../../../mips64-buildroot-linux-gnu/bin/ld: src/libaubio.so: undefined reference to `SWAPS'
collect2: error: ld returned 1 exit status

Waf: Leaving directory `/home/autobuild/autobuild/instance-16/output-1/build/aubio-152d6819b360c2e7b379ee3f373d444ab3df0895/build'
Build failed
```

Indeed there is a missing definition of the `SWAPS` macro in
`/src/io/sink_flac.c` file.
This commit copy the `SWAPS` definition from the
`/src/io/sink_wavwrite.c` file in `sink_flac.c` to fix this issue.

Signed-off-by: Thomas Perale <thomas.perale@mind.be>